# experiment parameter
sample_rate: 16000
frame_size: 320
fft_size: 161
frame_shift: 160
lr: 0.0002
max_epoch: 20
epsilon: 0.0000001
eval_steps: 5000
num_train: 320000
speech_len: 96000

# server setting
cuda_ids: '0'
batch_size: 4
num_workers: 0  # debug this is must set 0

workspace: 'CRN'

## environment parameter  107
#speech_file: '/data01/data_zkh/WSJ_datasets/long_wav_same_as_wang.bin'
#noise_file: '/data01/data_zkh/enhancement_data/long_wav.bin'
#eval_file: '/data01/data_zkh/WSJ_datasets/WSJ0_test_samps/test_ADTbabble_snr-5_unseen.samp'
#test_path: '/data01/data_zkh/WSJ_datasets/WSJ0_test_samps/'
#
#output_dir: '/data01/zhaofei/result/'
#tr_snr: [ -5, -4, -3, -2, -1, 0 ]


# environment parameter  61 /data01/zhaofei/data/CRN_data/long_wav.bin
speech_file: '/data01/zhaofei/data/CRN_data/WSJ_datasets/long_wav_same_as_wang.bin'
noise_file: '/data01/zhaofei/data/CRN_data/long_wav.bin'
eval_file: '/data01/zhaofei/data/CRN_data/WSJ_datasets/WSJ0_test_samps/test_ADTbabble_snr-5_unseen.samp'
test_path: '/data01/zhaofei/data/CRN_data/WSJ_datasets/WSJ0_test_samps/'
#train_lst: '/data_zkh/data_environment/tr_si84.mat'
#cv_lst: '/home/imu_speech2/zhangkanghao/se-code/Model/scps/cv_wsj.scp'
output_dir: '/data01/zhaofei/data/CRN_data/hyf/result'
tr_snr: [ -5, -4, -3, -2, -1, 0 ]


## environment parameter  zhaofei
#speech_file: '/mnt/raid2/userspace_hdd/zhaofei/data/WSJ_datasets/long_wav_same_as_wang.bin'
#noise_file: '/mnt/raid2/userspace_hdd/zhaofei/data/enhancement_data_wsj0si84/long_wav.bin'
#eval_file: '/mnt/raid2/userspace_hdd/zhaofei/data/WSJ_datasets/WSJ0_test_samps/test_ADTbabble_snr-5_unseen.samp'
#test_path: '/mnt/raid2/userspace_hdd/zhaofei/data/WSJ_datasets/WSJ0_test_samps/'
##train_lst: '/data_zkh/data_environment/tr_si84.mat'
##cv_lst: '/home/imu_speech2/zhangkanghao/se-code/Model/scps/cv_wsj.scp'
#output_dir: '/mnt/raid2/userspace_hdd/zhaofei/result/'
#tr_snr: [ -5, -4, -3, -2, -1, 0 ]
